### PR TITLE
Broadway

### PR DESCRIPTION
**Pull request by Galmeno**
new map test
some fiddling with the folders

### CODE REVIEW

**Review by drzel — CHANGES_REQUESTED** [review]
1. fortress/package/broadway_b1/maps/broadway_b1.bsp
2. fortress/package/maps/broadway_b1/broadway_b1.bsp

Map in twice here. Don't need number 2.

Let's get rid of the .gitkeep file as well.

**Comment by Galmeno** [comment]
> 1. fortress/package/broadway_b1/maps/broadway_b1.bsp
> 2. fortress/package/maps/broadway_b1/broadway_b1.bsp
> 
> Map in twice here. Don't need number 2.
> 
> Let's get rid of the .gitkeep file as well.
Done
[gitkeep](https://github.com/FortressOne/map-repo/pull/237/commits/50d0ecec0ab2829c9eb80f1773fd650dcf0ddbe1)
[bsp](https://github.com/FortressOne/map-repo/pull/237/commits/4bb5f1abb8706c87a81da354bfc45f7b7a3e6206)

**Comment by drzel** [comment]
Hrmm, I'm still seeing fortress/package/maps/broadway_b1/broadway_b1.bsp

**Comment by Galmeno** [comment]
Ok, done again :)

**Comment by drzel** [comment]
fortress/package/maps/broadway_b1/broadway_b1.txt should be at fortress/package/broadway_b1/maps/broadway_b1.txt

**Comment by Galmeno** [comment]
ok, removed txt instead and replaced bsp

**Comment by drzel** [comment]
You now have ecce gratum in twice and are missing models.

**Comment by Galmeno** [comment]
> You now have ecce gratum in twice and are missing models.

Solved.

**Pull request merged**
